name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      filename: addon-spanish-${{ github.ref_name }}.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Release
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          filename: ${{ env.filename }}
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.filename }}
