name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      filename: addon-spanish-${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Release
        run: |
          ADDON_NAME="$(grep -rEho "^namespace Addons\\\\Languages\\\\([^\\\\]+)" Controllers/ | sed 's:.*\\::')"
          git archive --format=tar --prefix="$(echo $ADDON_NAME)/" HEAD -o archive.tar
          tar -xf archive.tar
          rm -rf "$(echo $ADDON_NAME)"/.github/
          zip -r ${{ env.filename }}.zip "$ADDON_NAME"
          tar -zcvf ${{ env.filename }}.tar.gz "$ADDON_NAME"'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.filename }}.zip
            ${{ env.filename }}.tar.gz
