name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2, supportpal/language-tools

      - name: PHP Syntax Check
        uses: overtrue/phplint@8.0
        with:
          path: .
          options: --exclude=vendor

      - name: Check out English
        uses: actions/checkout@v3
        with:
          repository: supportpal/addon-language-english
          path: addon-language-english/
          ref: master

      - name: Code Quality
        run: |
          language-tools compare addon-language-english/Lang/en/ Lang/es
